import type { StackPack } from './types.js';

/**
 * Stack «tienda online con Medusa como verdad», destilado de certera-webs
 * (baliri-supp y baliri-care, Certera Dist, S.L.), en producción y vendiendo
 * desde septiembre de 2026. Cada regla viene de un fallo real o de una
 * corrección del dueño; el «por qué» es el incidente, no una opinión.
 */
export const medusaCommerceStack: StackPack = {
  id: 'medusa-commerce',
  version: '1.1.0',
  title: 'Tienda online B2C con Medusa como verdad, cobro propio con Stripe y web estática',
  tag: 'stack:medusa-commerce',
  origin: 'certera-webs (github.com/devwspito/certera-webs) · baliri-supp y baliri-care · sep-2026',
  starter: {
    repository: 'github.com/devwspito/commerce-starter',
    clone: 'gh repo create <org>/<proyecto> --private --template devwspito/commerce-starter --clone && cd <proyecto> && pnpm install && (cd services/medusa && pnpm install --ignore-workspace)',
    configure: 'cp marca.ejemplo.json marca.json && pnpm nueva-tienda marca.json',
    briefTemplate: 'marca.ejemplo.json: razón social, CIF (se valida el dígito de control), ciudad, marca en minúsculas, canal de Medusa, dominio https, IVA 4/10/21, tema claro o cálido y colores (el contraste AA se calcula solo).',
    ownerOnly: [
      'Cuentas propias del dueño (nunca de terceros): Stripe, Railway, proyecto de Firebase/Google y dominio.',
      'Datos legales LSSI: domicilio social, teléfono y correo; sin ellos la publicación se corta a propósito.',
      'Tipos de IVA confirmados con su gestor.',
      'Catálogo real (su inventario), fotos originales del fabricante y campañas oficiales de sus marcas.',
      'Panel de Stripe: numeración de facturas por cuenta, envío de facturas por correo y dirección fiscal.',
      'Secretos del publicador nocturno y la variable PUBLICAR_ACTIVO=true cuando todo lo anterior exista.',
    ],
  },
  useWhen: [
    'Una o varias tiendas B2C de una misma sociedad, con catálogo, stock, packs, cupones, suscripciones y facturación.',
    'El dueño quiere gestionarlo TODO desde un panel (productos, fotos, precios, stock, promociones, pedidos, envíos, reembolsos, textos de portada).',
    'Se necesita una web rapidísima y barata de servir (CDN) y un camino del dinero auditable y probado.',
  ],
  avoidWhen: [
    'Marketplace multi-vendedor o multi-sociedad con liquidaciones: Medusa v2 no tiene multi-tienda en el panel (la separación es por canal de venta).',
    'Catálogos de decenas de miles de referencias con búsqueda facetada en servidor: el buscador de este stack filtra en el navegador.',
  ],
  architecture: {
    layout: [
      'monorepo pnpm',
      '├─ apps/<tienda>/        Next.js 15 con `output: "export"` (estático) · site.config.ts = TODO el texto visible · shop.config.ts',
      '├─ packages/ui/          kit compartido: CartProvider, CartView, ProductCard, Muro, Nav, Buscador, Bienvenida… (CSS Modules)',
      '├─ packages/content/     tipos del catálogo + data/<tienda>.shop.json y <tienda>.contenido.json GENERADOS por el sync',
      '├─ packages/tokens/      base.css, motion.css, gestos.css, themes/<tienda>.css',
      '├─ services/checkout/    cobro en Node 22 (TS directo con --experimental-strip-types) + Postgres + Stripe por fetch',
      '├─ services/medusa/      Medusa v2 FUERA del workspace (propio lockfile) + módulos propios (contenido, proveedor de pago)',
      '├─ scripts/              sync Medusa→JSON, importadores, porteros `verificar-*.mjs`, publicador',
      '├─ specs/NNN-*/          spec-driven: spec, plan, tasks por cada cambio no trivial',
      '└─ .github/workflows/publicar.yml   publicación nocturna con porteros en modo duro',
    ].join('\n'),
    principles: [
      'MEDUSA ES LA VERDAD Y LAS WEBS SON ESCAPARATE: todo lo que el dueño cambia vive en Medusa; la web es un reflejo generado por `pnpm sync` y compilado.',
      'Stripe es la verdad del DINERO; el servicio de cobro traduce entre los dos y nunca decide precios que no salgan del catálogo.',
      'El navegador nunca manda precios: solo ids, cantidades, plan, versión del catálogo, cupón y correo.',
      'Una única función de valoración (`prepararCobro`) alimenta la previsualización del carrito y el cobro: lo que se ve es lo que se cobra, con prueba de paridad.',
      'Todo lo que se publica pasa porteros de build deterministas; lo que es un aviso en desarrollo corta la publicación con `PUBLICO=1`.',
      'Denegar por defecto en catálogo, orígenes, CSP y cookies.',
    ],
  },
  technology: [
    { layer: 'Web', choice: 'Next.js App Router, export estático', version: '15.x (React 19)', notes: 'Sin servidor: Firebase Hosting (CDN). cleanUrls, trailingSlash false, CSP por cabeceras de hosting.' },
    { layer: 'Monorepo', choice: 'pnpm workspaces', version: 'pnpm 9.15 · `packageManager` fijado', notes: 'services/medusa excluido del workspace (`!services/medusa`) e instalado con --ignore-workspace.' },
    { layer: 'Backend de comercio', choice: 'Medusa', version: 'v2.19', notes: 'Panel en español (Ajustes → Perfil → Idioma, cookie `lng`). Módulos propios en src/modules. Volumen para fotos en /app/.medusa/server/static.' },
    { layer: 'Cobro', choice: 'Servicio propio Node', version: 'Node 22, TS sin compilar (--experimental-strip-types)', notes: 'Sin parameter properties en constructores. Stripe por fetch form-encoded. Pruebas con node:test.' },
    { layer: 'Pagos', choice: 'Stripe Checkout + Billing', version: 'API 2025-03-31.basil (webhook fijado)', notes: 'Webhook creado por API; eventos checkout.session.completed, invoice.paid, charge.refunded.' },
    { layer: 'Datos', choice: 'PostgreSQL (Railway)', version: '16+', notes: 'BD `railway` = cobro; BD `medusa` = Medusa. Acceso de mantenimiento: `railway connect Postgres` + `\\c medusa`.' },
    { layer: 'Caché/colas Medusa', choice: 'Redis (Railway)', version: '7', notes: '' },
    { layer: 'Hosting API', choice: 'Railway', version: 'CLI fijado @railway/cli@5.49.2', notes: 'Dos contextos de despliegue: raíz (cobro) y services/medusa. `railway up --ci` espera al resultado real.' },
    { layer: 'Hosting web', choice: 'Firebase Hosting en la cuenta del CLIENTE/dueño', version: 'API REST de Hosting', notes: 'Publicación con `scripts/publicar-firebase.mjs` (token de usuario o cuenta de servicio). Nunca en cuentas de terceros.' },
    { layer: 'CI', choice: 'GitHub Actions', version: 'acciones fijadas por SHA', notes: 'Nocturno 22:00 UTC: sync → ¿cambios? → build+porteros → test → cobro primero → web → commit del catálogo.' },
    { layer: 'Pruebas de UI', choice: 'vitest + Testing Library', version: 'vitest 3+', notes: '' },
    { layer: 'QA en vivo', choice: 'Playwright (Chromium y WebKit)', version: '1.63', notes: 'Anchos 320, 360, 393, 430, 768, 1440.' },
    { layer: 'Imágenes', choice: 'Python + Pillow', version: 'Pillow 10', notes: 'Recorte de fondo a WebP transparente; encuadre normalizado por manifiesto.' },
    { layer: 'Correo transaccional', choice: 'Resend (opcional)', version: '', notes: 'Sin remitente el correo queda en cola y el panel ofrece copiarlo a mano; la factura la envía Stripe.' },
  ],
  team: [
    { id: 'commerce-architect', title: 'Arquitecto de comercio', owns: ['límites Medusa ↔ cobro ↔ Stripe ↔ web', 'contratos (JSON del catálogo, cuerpo de /checkout, webhooks)', 'specs/NNN'], mustNot: ['meter lógica de precios en la web', 'duplicar referencias para modelar packs'] },
    { id: 'medusa-engineer', title: 'Ingeniero Medusa', owns: ['services/medusa', 'workflows de core-flows', 'módulos propios (contenido, proveedor de pago)', 'widgets y rutas de admin', 'sync e importadores'], mustNot: ['escribir precios o canales con productModule.update*', 'borrar datos por SQL sin soltar antes reservas'] },
    { id: 'payments-engineer', title: 'Ingeniero del camino del dinero', owns: ['services/checkout', 'webhook de Stripe', 'facturas e IVA', 'suscripciones', 'sala de espera'], mustNot: ['aceptar precios del navegador', 'responder 200 a un evento que no se procesó'] },
    { id: 'storefront-engineer', title: 'Ingeniero de tienda', owns: ['apps/*', 'packages/ui', 'packages/tokens', 'carrito y previsualización'], mustNot: ['escribir texto visible fuera de site.config.ts', 'estirar, recortar o enmascarar fotos de producto'] },
    { id: 'content-designer', title: 'Contenido y copy', owns: ['site.config.ts', 'fichas', 'mensajes de error', 'legales'], mustNot: ['inventar datos (van con pending())', 'definirse por negación o sobreexplicar'] },
    { id: 'visual-qa', title: 'QA visual y en vivo', owns: ['Playwright contra producción', 'capturas por ancho', 'compra real de prueba'], mustNot: ['dar por buena una pantalla sin mirarla', 'confundir tests verdes con tienda buena'] },
    { id: 'ops', title: 'Operación y despliegue', owns: ['Railway', 'Firebase', 'DNS', 'secretos', 'workflow nocturno'], mustNot: ['publicar la web antes que el cobro', 'dejar main sin empujar (el nocturno redespliega main)'] },
  ],
  sections: [
    {
      id: 'medusa-verdad',
      title: 'Medusa es la verdad; la web es escaparate',
      summary: 'Todo lo gestionable vive en Medusa y baja a la web por un sync determinista.',
      rules: [
        { id: 'panel-lo-gestiona-todo', rule: 'Productos, fotos, precios, stock, packs, promociones, listas de precios, pedidos, envíos, reembolsos, clientes y textos de portada/legales se gestionan desde el panel de Medusa.', why: 'El dueño exigió «todo, absolutamente todo desde Medusa, al nivel de Shopify». Cada cosa que vive en el repo es un favor que hay que pedir a un técnico.', howToApply: 'Si algo no tiene sitio en Medusa, se crea: módulo `contenido` (tabla propia + ruta /admin/contenido + página de admin) para textos, teléfono, domicilio y envío. El sync lo baja a <tienda>.contenido.json.' },
        { id: 'sync-sin-merge', rule: 'El sync publica exactamente lo que dice el panel, también «nada».', why: 'Un merge con lo previo impedía vaciar campos y dejó un tachado «rebajado de 29,29 a 29,29».', howToApply: 'Sin `previo ?? …` en campos editables. Si un campo queda vacío en Medusa, queda vacío en la web. Portero que corta tachado ≤ precio.' },
        { id: 'tiendas-por-canal', rule: 'Varias tiendas = varios canales de venta en una sola store de Medusa.', why: 'Medusa v2 no tiene multi-tienda en el panel (`useStore()` es singular).', howToApply: 'Canal por tienda, handle con prefijo de tienda (`<tienda>-<slug>`). Emparejar siempre por handle: los ids de catálogo tipo p01 chocan entre tiendas.' },
        { id: 'panel-en-espanol', rule: 'El panel se deja en el idioma del dueño.', why: 'Un panel en inglés no se usa.', howToApply: 'Ajustes → Perfil → Idioma (cookie `lng` por navegador). Renombrar la store a la razón social.' },
      ],
    },
    {
      id: 'catalogo-stock',
      title: 'Catálogo y existencias',
      summary: 'Sin stock no se vende; disponibilidad derivada solo de available_quantity.',
      rules: [
        { id: 'sin-stock-no-se-vende', rule: 'La disponibilidad es `stock > 0`, a secas.', why: '`manage_inventory === false || stock > 0` puso a la venta 16 sérums que la empresa no tenía.', howToApply: 'Portero que corta si algo está disponible sin control de stock; probarlo invirtiendo el caso. Buscar `|| x === false` y `continue` que salten la comprobación.' },
        { id: 'available-no-stocked', rule: 'La web y el cobro leen la MISMA cifra: available_quantity.', why: 'La web miraba stocked_quantity y la caja vendía con available_quantity.', howToApply: 'Una sola función de existencias en el cobro; el sync usa la misma.' },
        { id: 'sku-articulo-inventario', rule: 'El SKU del artículo de inventario debe coincidir con el de su variante.', why: 'Medusa enlaza variante↔inventario por id, no por SKU; tras renombrar, 8 referencias decían sin stock con el almacén lleno.', howToApply: 'Script `alinear-sku-inventario.mjs` tras cualquier renombrado; el sync avisa de desfases.' },
        { id: 'retirados-vs-sin-stock', rule: 'Producto real sin unidades = publicado con 0 y «próximamente/Avísame». Producto inventado o que no existe en el inventario del cliente = se borra.', why: 'El dueño: «no es un borrador, simplemente no hay stock ahora mismo».', howToApply: 'La fuente de qué existe es el inventario del cliente (p. ej. informe Seller de Amazon). Nunca pasar a borrador algo que solo está agotado.' },
        { id: 'perfil-envio', rule: 'Todo producto lleva shipping_profile_id.', why: 'Sin él el botón «enviar» del panel da 400.', howToApply: 'El importador lo asigna; script de reparación para los viejos.' },
        { id: 'version-catalogo', rule: 'El catálogo lleva `version` (hash) y viaja en el POST; el cobro responde `catalogo_desactualizado`.', why: 'Una web vieja en caché contra un cobro nuevo rechazaba líneas sin explicación.', howToApply: 'El sync calcula el hash; el carrito lo manda; el error invita a recargar.' },
      ],
    },
    {
      id: 'precios-promociones',
      title: 'Precios, cupones, descuentos automáticos y listas de precios',
      summary: 'Medusa decide el descuento en vivo; Stripe lo cobra con un cupón de un uso.',
      rules: [
        { id: 'euros-decimales', rule: 'La API de Medusa v2 habla en EUROS DECIMALES (29.29); Stripe y el cobro en céntimos.', why: 'Se mandaron 2929 y un carrito de 84,58 € salió como 8.458 €.', howToApply: 'Conversión SOLO en el borde (`aEuros()` / `toCents()`), con pruebas.' },
        { id: 'cupon-en-vivo', rule: 'El cobro valida el cupón contra Medusa en cada valoración (`GET /admin/promotions/{code}`) y crea un cupón de Stripe de un solo uso con `amount_off` exacto.', why: 'Stripe Checkout no admite líneas negativas ni recalcula porcentajes igual.', howToApply: 'Errores tipados: cupon_no_valido, cupon_caducado, cupon_agotado, cupon_no_aplica. Código en metadata para el webhook.' },
        { id: 'usos-contados-local', rule: 'El límite de usos se cuenta en los pedidos cobrados propios.', why: 'Medusa no expone incrementar `promotion.used` fuera de completeCartWorkflow.', howToApply: '`count(*) FROM orders WHERE cupon_codigo = $1` con índice parcial; carrera del último uso aceptada y documentada.' },
        { id: 'automatico-vs-codigo', rule: 'Con descuento automático y código a la vez se aplica el MAYOR.', why: 'Medusa no dice si combinan; sumar regalaba dinero.', howToApply: '`elegirMejorDescuento` puro y probado.' },
        { id: 'target-order', rule: 'Promociones porcentuales generales van con target_type `order`.', why: 'Con `items` sin reglas el evaluador devolvía cupon_no_aplica.', howToApply: 'Crear promociones de bienvenida o globales sobre el pedido.' },
        { id: 'listas-de-precios', rule: 'Las listas de precios se leen de `/admin/price-lists/{id}/prices`; la lista vigente es el precio y el base pasa a tachado.', why: 'El endpoint de productos NO devuelve precios de lista: el primer intento lo asumió y falló en vivo.', howToApply: 'Reglas por grupo/cantidad/región se AVISAN y no se aplican; dos listas vigentes para la misma variante paran el sync.' },
        { id: 'preview-tiempo-real', rule: 'El carrito muestra el descuento en tiempo real con `POST /previsualizar` (mismo cuerpo que /checkout, solo lectura).', why: '«Aplica en Stripe pero no se ve en el carrito, y sí o sí tiene que verse.»', howToApply: 'Debounce 400 ms + AbortController; errores de cupón al instante; si falla la red, cálculo local con aviso y el pago sigue. Prueba de paridad con el total de Stripe.' },
        { id: 'bienvenida-una-vez', rule: 'Un descuento «una vez por persona» exige correo: se valida contra pedidos cobrados y se fija en Stripe (`customer_email`).', why: 'Un carrito anónimo no puede prometer «una vez por persona».', howToApply: 'Pop-up una vez por navegador que pide el correo, `POST /bienvenida` devuelve el código y lo aplica al carrito; códigos con prefijo (BIENVENIDA*) heredan la regla sin tocar código.' },
      ],
    },
    {
      id: 'packs',
      title: 'Packs como kits de inventario',
      summary: 'Un pack es un producto con precio propio y sin stock propio: el stock es el de sus piezas.',
      rules: [
        { id: 'kit-de-inventario', rule: 'Pack = producto de Medusa cuya variante tiene «kit de inventario» (piezas + required_quantity).', why: 'Modelarlos como producto con stock propio duplicaba referencias y vendía la misma unidad dos veces.', howToApply: 'Medusa reserva y descuenta las piezas. El cobro manda el pack como UNA línea (`<TIENDA>-PACK-<SLUG>`); la comprobación previa de stock mira las piezas.' },
        { id: 'portero-packs', rule: 'Un pack tiene ≥2 unidades, solo productos existentes y precio ≤ suma de piezas.', why: 'Un pack que cuesta más que sus piezas es un error de catálogo que el cliente ve.', howToApply: 'Portero en verificar-catalogo; ahorro calculado, nunca escrito.' },
        { id: 'fotos-de-pack', rule: 'La foto del pack se compone con las de sus piezas.', why: 'Los packs salían sin foto en el panel.', howToApply: 'El subidor de fotos da a cada pack la primera foto de sus piezas.' },
        { id: 'nada-de-payment-links', rule: 'No se vende con Payment Links creados a mano en Stripe.', why: 'Llegó una venta real sin tienda, sin catálogo y sin dirección: ni pedido ni cliente en Medusa.', howToApply: 'Compartir la ficha de la web o crear el pack en Medusa. Aun así el espejo admite «venta fuera de la web» como artículo libre con aviso para pedir la dirección.' },
      ],
    },
    {
      id: 'cobro-stripe',
      title: 'Camino del dinero: cobro y webhook de Stripe',
      summary: 'El pedido existe porque Stripe lo cuenta en el webhook, no porque el cliente vuelva a «gracias».',
      rules: [
        { id: 'webhook-firma-idempotencia', rule: 'Webhook con firma oficial, idempotencia por id de evento y distinción «guardado» vs «terminado».', why: 'Un proceso que moría tras el commit dejaba pedidos sin reserva ni correo para siempre, y Stripe veía 200.', howToApply: 'Tabla de eventos con completado_at; un evento a medias se remata en el reintento. Se guarda el esqueleto del evento, no los datos personales.' },
        { id: 'version-api-dual', rule: 'Leer los campos de Stripe en las DOS formas (basil y anteriores).', why: 'En basil `invoice.lines[0].subscription`, `invoice.payment_intent` y `session.shipping_details` cambiaron de sitio: las renovaciones no creaban pedido y el webhook respondía 200.', howToApply: 'Lectores `suscripcionDe`, `intentoDe`, `direccionDe`. La versión fijada del endpoint se ve con GET /v1/webhook_endpoints; no está en el repo.' },
        { id: 'modo-cruzado', rule: 'Rechazar eventos cuyo livemode no coincide con la clave.', why: 'Un webhook de pruebas apuntando a producción colaría pedidos falsos.', howToApply: '`esModoPrueba()` único (sk_test_ y rk_test_). Al probar a mano, el evento debe llevar livemode: true.' },
        { id: 'payment-status', rule: 'Solo `payment_status = paid` crea pedido.', why: 'Métodos asíncronos completan la sesión sin cobro.', howToApply: 'Comprobación en el webhook con prueba.' },
        { id: 'suscripcion-sin-envio', rule: 'En modo suscripción no hay `shipping_options`: el envío va incluido y el carrito no lo suma.', why: 'El carrito enseñaba 22,86 € y Stripe cobraba 17,91 €.', howToApply: 'Misma regla en `calcularEnvio` para preview y cobro.' },
        { id: 'suscripcion-intent', rule: 'En sesiones de suscripción el payment_intent se resuelve desde la factura.', why: 'La sesión trae payment_intent null y el espejo caía al proveedor maniquí.', howToApply: '`intentoDeSesionSuscripcion`: factura de la sesión, si no la latest_invoice expandida.' },
        { id: 'contacto-obligatorio-live', rule: 'Con clave live el cobro se niega si falta el correo de contacto publicado.', why: 'Vender sin forma de contacto incumple LSSI y deja al cliente sin salida.', howToApply: '`comprobarContactoPublicado` antes de valorar.' },
        { id: 'claves-idempotencia', rule: 'Clave de idempotencia por INTENTO, no por carrito.', why: 'Con clave por contenido, 40 compras iguales se bloqueaban con 409 idempotency_key_in_use.', howToApply: '`crypto.randomUUID()` por petición; el reintento reutiliza la suya.' },
      ],
    },
    {
      id: 'conciliacion-medusa',
      title: 'Conciliación Stripe ↔ cobro ↔ Medusa',
      summary: 'Cada cobro crea su pedido en Medusa con el pago REAL enlazado; Medusa es dueño de reservas y envíos.',
      rules: [
        { id: 'pedido-espejo', rule: 'checkout.session.completed / invoice.paid → borrador → convert-to-order → payment-collection → payment-session con el pi_ real → authorize.', why: 'Sin pedido en Medusa el dueño no podía enviar, devolver ni ver clientes.', howToApply: '`shipping_methods[].name` es obligatorio. Idempotente por `metadata.stripe_session_id` + `orders.medusa_order_id`; si murió a medias, se reanuda solo el pago.' },
        { id: 'proveedor-pago-propio', rule: 'Proveedor de pago propio en Medusa que ESPEJA el PaymentIntent existente (no cobra) y reembolsa de verdad.', why: 'Con mark-as-paid el pago quedaba en `pp_system_default`, un maniquí: dos pedidos figuraban «refunded» con CERO reembolsos en Stripe. El conector oficial solo crea intents nuevos.', howToApply: 'Módulo `stripe-checkout` → `pp_stripe-checkout_<marca>`: verifica `succeeded` ⇒ CAPTURED; refund por API de Stripe con fetch (stripe no es dependencia de Medusa). Probado con reembolso real desde el panel.' },
        { id: 'reservas-de-medusa', rule: 'convert-to-order RESERVA stock: Medusa pasa a ser el dueño de reservas y descuento.', why: 'Reservar también en el cobro apartaba cada unidad dos veces.', howToApply: 'El cobro no reserva lo que tiene medusa_order_id; liberar = cancelar el pedido en Medusa (400 si ya se expidió: se registra sin romper).' },
        { id: 'vuelta-envio', rule: 'Envío en el panel → subscriber `shipment.created` → POST firmado HMAC al cobro → marca enviado y avisa, sin tocar stock.', why: 'El payload solo trae el fulfillment id.', howToApply: 'Resolver el pedido por el link order↔fulfillment con Query; `MEDUSA_WEBHOOK_SECRET` en los dos servicios.' },
        { id: 'soltar-antes-de-borrar', rule: 'Soltar la reserva en Medusa ANTES de borrar la fila que la rastrea.', why: 'Borrar en SQL dejaba unidades bloqueadas para pedidos inexistentes, inalcanzables desde SQL.', howToApply: 'Limpiezas por endpoint (`/panel/limpiar-pruebas` con confirmación explícita), nunca por migración. Detector de huérfanas que re-pregunta antes de soltar.' },
        { id: 'pedidos-no-se-borran', rule: 'Los pedidos de Medusa no se borran por API; los de prueba se archivan y se purgan con una ruta de admin propia con tres condiciones.', why: 'deleteFulfillments no existe a propósito y un envío expedido no se cancela.', howToApply: '`POST /admin/pedidos-de-prueba/borrar {aplicar:true}` (archivado + cs_test_/sin sesión + correo de prueba). Expedidos: cancelar el fulfillment por SQL con autorización explícita.' },
        { id: 'salud-espejo', rule: '`/salud` con token enseña conPedido / conError / conPagoReal.', why: 'Un espejo fallido no se ve en ningún otro sitio.', howToApply: 'Reintento manual `/panel/reintentar-pedido-medusa` idempotente.' },
      ],
    },
    {
      id: 'facturacion-iva',
      title: 'Facturación e impuestos',
      summary: 'La factura la emite y envía Stripe al cobrar, con el IVA de cada tienda desglosado.',
      rules: [
        { id: 'factura-stripe', rule: 'Cada pago lleva `invoice_creation` (suscripción: Stripe ya factura cada renovación).', why: 'El módulo propio numeraba sin generar ni enviar documento: nadie facturaba.', howToApply: 'customer_creation always, billing_address_collection required, tax_id_collection, pie con marca + razón social + CIF. Guardar id/número/URL/PDF en el pedido y enseñarlos en Medusa («Descargar PDF»).' },
        { id: 'iva-por-tienda', rule: 'IVA inclusivo por tienda (p. ej. complementos 10 %, cosmética 21 %) como tax_rates de Stripe buscados o creados una vez.', why: 'Un 21 % para todo era falso para complementos.', howToApply: 'El tipo lo confirma el gestor del cliente. Si Stripe no responde el tipo, se rechaza el pago antes que emitir mal.' },
        { id: 'envio-como-linea', rule: 'El envío va como línea con IVA, no como shipping_options, y su importe en metadata.', why: 'Con tipos manuales Stripe no grava la tarifa de envío.', howToApply: 'El webhook lee las dos formas por las sesiones abiertas antes del cambio.' },
        { id: 'ajustes-de-panel', rule: 'Numeración por cuenta, envío de facturas por correo y dirección fiscal se configuran en el panel de Stripe.', why: 'No hay API para esos ajustes.', howToApply: 'Checklist para el dueño en el bootstrap.' },
      ],
    },
    {
      id: 'carga-colas',
      title: 'Picos de tráfico: sala de espera del pago',
      summary: 'Lo único saturable es POST /checkout; bajo avalancha se reparten turnos en vez de errores.',
      rules: [
        { id: 'sala-de-espera', rule: 'Cola FIFO: sin hueco, /checkout responde 202 con turno; la web sondea `GET /sala/<turno>` y repite el pago al ser admitida.', why: 'Stripe limita escrituras/s y el plan no tenía réplicas.', howToApply: 'SALA_CAPACIDAD, SALA_ADMISION_POR_SEGUNDO, TTL de turno 90 s, abandono 60 s, tope de espera → 503. Almacén aislado para pasar a Redis si hay réplicas.' },
        { id: 'cupos', rule: 'Cupos por IP y globales por ruta, con techo real.', why: 'Detrás de CGNAT varios compradores comparten IP.', howToApply: '/checkout 120/min por IP, /previsualizar igual, formularios estrechos.' },
      ],
    },
    {
      id: 'storefront-ui',
      title: 'Tienda: lineamientos de interfaz',
      summary: 'Full ecommerce: el producto por encima del pliegue, patrón de las grandes tiendas, móvil primero.',
      rules: [
        { id: 'full-ecommerce', rule: '«Menos información, más estética»: la web vende producto, no explica la empresa.', why: '«Las webs están muy genéricas, tiene que ser full ecommerce.» El primer «Añadir» caía a 2.413 px.', howToApply: 'Primera tarjeta de producto ≤ ~360 px del top en escritorio y móvil. ShopHeader compacto (migas + nombre + cuenta + filtros). Nada de cabeceras de 188 px en páginas de tienda.' },
        { id: 'replica-los-grandes', rule: 'Replicar patrones de tiendas grandes (Zalando) en vez de inventar.', why: '«Replica Zalando y ya está, para qué inventar.»', howToApply: 'Buscador con desplegable (miniatura, nombre, formato, precio, teclado), orden (destacados, precio, nombre, precio por toma), fichas con <details> nativos, venta cruzada, home muro comercial (campaña de marca, producto, categorías).' },
        { id: 'secciones-como-etiquetas', rule: 'Un titular de sección es una etiqueta de catálogo, no una portada.', why: 'Secciones de 186 px de relleno empujaban el producto fuera.', howToApply: '«Productos destacados», «Categorías», «Novedades». Tamaños contenidos.' },
        { id: 'movil-primero', rule: 'Móvil primero; sin scroll horizontal; filtros en una fila deslizable.', why: 'Los chips ocupaban 4 líneas y 240 px.', howToApply: 'Validar en Chromium y WebKit a 320, 360, 393, 430, 768 y 1440. La rejilla móvil (1 o 2 columnas) la decide el dueño: preguntarlo.' },
        { id: 'estandar-de-tarjeta', rule: 'Todas las tarjetas de producto con el mismo marco y la misma escala visual en toda la web.', why: '«Las dimensiones deben verse como el tercero, todos con el tercero, y debe ser un estándar en toda la web.»', howToApply: 'Un solo componente de marco (fondo, margen, object-fit contain), reutilizado en categorías, rejilla, buscador y marcas.' },
        { id: 'carrito-honesto', rule: 'El carrito enseña el total que se va a cobrar, con descuento y envío, y cada error del cobro con su acción.', why: 'Diferencias carrito/Stripe destruyen la confianza.', howToApply: 'Errores mapeados (sin_stock, not_for_sale, catalogo_desactualizado, saturado, cupon_*) nombrando el producto y con botón de salida.' },
        { id: 'marca-y-sociedad', rule: 'La marca de la tienda es lo que ve el cliente; la sociedad aparece en todo lo legal y de empresa.', why: 'El dueño lo exige: «la empresa matriz es Certera Dist en ambas».', howToApply: 'Marca en nombre, wordmark, títulos, icono, OG y correos; razón social y CIF en legales, proveedores y pie de factura. Marca de cara al cliente centralizada en un módulo del cobro.' },
      ],
    },
    {
      id: 'fotos-producto',
      title: 'Fotografía de producto',
      summary: 'Fotos reales, enteras, proporcionales y sin fondo; la fuente de verdad es Medusa.',
      rules: [
        { id: 'fotos-desde-medusa', rule: 'Las fotos se suben a Medusa y el sync las descarga a `apps/*/public/productos/`.', why: 'La consulta no pedía `*images`, el mapeo escribía [] y la CSP habría bloqueado el CDN: subir fotos no llegaba nunca a la web.', howToApply: 'Pedir *images y thumbnail primero, componer el alt (Medusa no lo guarda), descargarlas al build. Volumen de Medusa en /app/.medusa/server/static (ruta de lectura no configurable).' },
        { id: 'sin-fondo', rule: 'Fotos de catálogo sin fondo blanco (WebP transparente), recortadas al contorno con margen uniforme.', why: 'Sobre fondos de color o al solaparse en tarjetas de marca aparecían «cuadritos» blancos.', howToApply: 'Inundación desde los bordes (solo el blanco conectado al borde), suavizado de 1 px, margen 4 %; sustituir en Medusa, no en la web.' },
        { id: 'nunca-alterar-producto', rule: 'Nada de personas generadas por IA, etiquetas reconstruidas, estirados, tapas enmascaradas, cuantización ni solapes.', why: 'Es material de marcas que autorizan su uso; alterarlo es un riesgo comercial y legal.', howToApply: 'Registrar la URL de origen de cada imagen importada; manifiesto de originales que protege frente a versiones dañadas en Medusa.' },
        { id: 'escala-visual', rule: 'Comparar el envase visible, no el lienzo: un tarro ancho no puede empequeñecer a un bote estrecho.', why: 'Escalas dispares entre tarjetas.', howToApply: 'Manifiesto de encuadres por producto + escala de área visual; portero que protege escala y píxeles originales.' },
        { id: 'campanas-de-marca', rule: 'Los banners de marca usan campañas verificadas del fabricante, nunca un producto del catálogo de relleno.', why: 'Un banner con un producto cualquiera no es una campaña.', howToApply: 'Procedencia en un JSON de fuentes y un doc por fecha.' },
      ],
    },
    {
      id: 'copy-contenido',
      title: 'Copy y contenido',
      summary: 'Titulares de 2-5 palabras; el dato antes que el adjetivo; nada inventado.',
      rules: [
        { id: 'leer-competencia', rule: 'Antes de escribir copy de un sector, leer tres competidores y medir.', why: '«Los copys son un maldito desastre, los humanos no hablamos así.» La competencia usa 2-5 palabras.', howToApply: 'Mediana de palabras por frase y % de frases ≤6 palabras antes y después (11,9 → 5,9 y 2 % → 58 %).' },
        { id: 'no-sobreexplicar', rule: 'Una idea por frase; borrar la tercera frase; prohibido definirse por negación.', why: '«Sobreexplicas todo, suena a IA.»', howToApply: 'No se recortan avisos de seguridad, modo de uso, incompatibilidades ni condiciones de devolución.' },
        { id: 'vocabulario-cliente', rule: 'Palabras del cliente final: «productos», no «referencias».', why: '«Referencias» es palabra de mayorista.', howToApply: 'Reescribir el texto importado de marketplaces ficha a ficha; nunca volcarlo.' },
        { id: 'pending-no-inventar', rule: 'Todo dato no confirmado viaja con pending() y se pinta marcado; la publicación exige que no quede ninguno obligatorio.', why: 'Inventar cifras o marcas en la web de una empresa es mentir a sus clientes y proveedores.', howToApply: '`pnpm pending` lista lo que falta. Nunca marcas inventadas; nunca logos ajenos sin acuerdo escrito.' },
        { id: 'texto-en-un-sitio', rule: 'Todo el texto visible sale de site.config.ts (y del contenido de Medusa).', why: 'Una palabra se cambia en un solo sitio.', howToApply: 'Ninguna página escribe cadenas sueltas.' },
        { id: 'generalizar-correcciones', rule: 'Cuando el dueño señala un fallo, formular la regla, barrer TODO el proyecto y, si es verificable, convertirla en portero.', why: '«No te puedo solucionar todo yo, debes aplicar esta esencia en todo.»', howToApply: 'Ejemplo: el titular se compara contra el catálogo en verificar-catalogo.' },
      ],
    },
    {
      id: 'accesibilidad-rendimiento',
      title: 'Accesibilidad y rendimiento',
      summary: 'WCAG 2.2 AA verificado en build; Lighthouse móvil ≥ 95.',
      rules: [
        { id: 'contraste-aa', rule: 'Contraste AA (4,5:1) comprobado sobre los temas activos antes de publicar.', why: 'Una tienda llegó con todas sus llamadas a la acción a 3,34:1 y los errores a 2,95:1.', howToApply: 'Portero verificar-contraste en el build.' },
        { id: 'movimiento', rule: 'Animaciones con transform/opacity, ease-out, <300 ms en UI, respetando prefers-reduced-motion; hover solo con puntero fino.', why: 'Movimiento que marea o que retrasa lo que el usuario mira.', howToApply: 'Revisión de animaciones antes de publicar cambios de UI.' },
        { id: 'dialogos', rule: 'Pop-ups y paneles: role=dialog, aria-modal, foco al abrir, Escape cierra, hoja inferior en móvil.', why: 'Un modal sin foco atrapa al teclado.', howToApply: 'Componente reutilizable probado con Testing Library.' },
      ],
    },
    {
      id: 'privacidad-legal',
      title: 'Privacidad y legal (España/UE)',
      summary: 'Sin cookies ni terceros; LSSI completo antes de publicar; consentimiento explícito para marketing.',
      rules: [
        { id: 'cero-cookies', rule: 'Ni cookies ni dominios de terceros; el carrito en localStorage (exento).', why: 'Poder decir «este sitio no usa cookies» evita el banner y es una ventaja.', howToApply: 'Portero verificar-cookies sobre el HTML construido; si alguien añade analítica, corta hasta actualizar la política.' },
        { id: 'lssi', rule: 'Razón social, CIF, domicilio, teléfono y correo publicados antes de vender (LSSI art. 10).', why: 'Sin domicilio el nocturno no puede publicar a propósito.', howToApply: 'verificar-legal lee el dato de <tienda>.contenido.json (no el código fuente: el pending() de respaldo bloquearía para siempre).' },
        { id: 'datos-minimos', rule: 'Los correos recogidos para un descuento solo sirven para ese fin salvo casilla de consentimiento.', why: 'Usar una lista sin consentimiento para ofertas es ilegal.', howToApply: 'Si se quiere marketing, añadir casilla explícita y registrar el consentimiento.' },
        { id: 'purgas-anonimizacion', rule: 'Purga de datos de prueba y función de anonimizar cliente.', why: 'Derecho de supresión y datos de prueba mezclados con reales.', howToApply: 'Migración con `anonimizar_cliente`; eventos de webhook sin datos personales.' },
      ],
    },
    {
      id: 'despliegue-operacion',
      title: 'Despliegue y operación',
      summary: 'Cobro antes que web, esperando el resultado real; todo en cuentas del dueño; main siempre empujado.',
      rules: [
        { id: 'cuentas-del-dueno', rule: 'Hosting, dominios y servicios en cuentas del dueño/cliente, nunca en cuentas de terceros.', why: 'Tener la web de un cliente en la cuenta de Google de otra empresa fue un «error gravísimo».', howToApply: 'Configuración de gcloud aparte por cliente; publicar con token de esa cuenta o una cuenta de servicio de su proyecto.' },
        { id: 'cobro-antes-que-web', rule: 'Desplegar el cobro, ESPERAR a que termine bien (`--ci`) y solo entonces la web.', why: 'La web publicada antes que el cobro enseñaba 21 productos a un cobro que conocía 8: unknown_product.', howToApply: 'Orden fijo en el workflow; si falla el cobro no se toca la web ni se commitea el catálogo.' },
        { id: 'dos-contextos-railway', rule: '`railway up` filtra con .railwayignore del directorio desde el que se lanza; hay dos contextos (raíz y services/medusa).', why: 'El .env de desarrollo de Medusa viajó a un build real.', howToApply: 'Portero verificar-despliegue-secretos simula cada contexto. Excluir .env*, .xlsx, .git.' },
        { id: 'startcommand', rule: 'No poner startCommand en railway.json si el Dockerfile ya define el arranque.', why: 'Medusa estuvo dos semanas sin desplegar: Railway dejaba el contenedor viejo en pie.', howToApply: 'Comprobar que el despliegue nuevo es el que sirve (versión en /salud).' },
        { id: 'firebase-por-api', rule: 'Publicar la web por la API de Hosting con un token.', why: '`firebase deploy` con cuenta de servicio daba 403 en firebase.googleapis.com.', howToApply: '`scripts/publicar-firebase.mjs` lee firebase.json/.firebaserc y sube por hashes; la cuenta de servicio con firebasehosting.admin + firebase.viewer + serviceUsageConsumer.' },
        { id: 'dominios-cname', rule: 'Subdominios por CNAME al sitio de Firebase; el certificado lo emite Firebase tras verificar.', why: 'Tocar los MX pierde el correo de la empresa.', howToApply: 'Solo CNAME/A del host de la tienda. Actualizar ALLOWED_ORIGINS y URLs de retorno del cobro cuando resuelvan.' },
        { id: 'csp-connect-src', rule: 'Al mover el cobro o cualquier API, actualizar la CSP connect-src en el mismo commit.', why: 'El navegador bloquea en silencio: nada falla al publicar.', howToApply: 'Portero verificar-cobro-csp compara NEXT_PUBLIC_CHECKOUT_URL con la CSP de cada tienda.' },
        { id: 'main-empujado', rule: 'Dejar main empujado tras cada despliegue manual.', why: 'El nocturno despliega main y redesplegaría lo viejo.', howToApply: 'Commit + push al terminar; nunca force.' },
        { id: 'nocturno-porteros', rule: 'El nocturno solo publica si hay cambios y todos los porteros pasan en modo duro; `forzar` para retoques de UI.', why: 'Automatizar sin red es automatizar la forma de romper la tienda de madrugada.', howToApply: 'Acciones fijadas por SHA, persist-credentials false, CLIs fijados.' },
      ],
    },
    {
      id: 'seguridad',
      title: 'Seguridad',
      summary: 'Orígenes permitidos, cabeceras, secretos fuera del repo y del chat, mínimo privilegio.',
      rules: [
        { id: 'origenes', rule: 'El cobro solo responde a orígenes permitidos; sin origen, nada útil.', why: 'El endpoint mueve dinero.', howToApply: 'ALLOWED_ORIGINS con las URLs reales de las tiendas (dominio y *.web.app).' },
        { id: 'claves-restringidas', rule: 'Clave restringida de Stripe (rk_live_) para Medusa con solo lo que necesita; API key secreta de Medusa para el cobro.', why: 'Una clave completa en un servicio secundario amplía el daño de una filtración.', howToApply: 'refunds:write + payment_intents:read para el proveedor de pago.' },
        { id: 'secretos-fuera-del-chat', rule: 'Ningún secreto se pega en el chat ni se transcribe de capturas; si ocurre, se rota.', why: 'Tokens pegados en chat quedaron expuestos.', howToApply: 'Variables en Railway/GitHub Secrets; el dueño las introduce él.' },
        { id: 'panel-token', rule: 'Rutas de panel con PANEL_TOKEN comparado en tiempo constante y proxy desde Medusa para no exponerlo al navegador.', why: 'El token en el navegador es un token público.', howToApply: 'Widgets de Medusa llaman a rutas /admin propias que añaden el token en servidor.' },
        { id: 'xss-jsonld', rule: 'JSON-LD y cualquier HTML inyectado escapados.', why: 'Se encontró XSS en el JSON-LD de producto.', howToApply: 'Serializar con escape de < y >.' },
      ],
    },
    {
      id: 'qa-en-vivo',
      title: 'Verificación en vivo',
      summary: 'Nada está hecho hasta verlo funcionar por el camino real de producción.',
      rules: [
        { id: 'comprar-de-verdad', rule: 'Probar comprando contra producción (sesión real que se caduca, o tarjeta de prueba en modo test).', why: 'El panel enseñaba perfectos productos que el cobro no podía vender.', howToApply: 'Crear la sesión desde el dominio real, leerla en Stripe (total, IVA, correo, factura) y caducarla.' },
        { id: 'navegador-no-tests', rule: 'Capturas por ancho y consola del navegador antes de dar una pantalla por buena.', why: 'Tests verdes no ven jerarquía, contraste ni CSP bloqueando.', howToApply: 'Playwright en Chromium y WebKit; recoger errores de consola; revisar a ojo representativas.' },
        { id: 'trampas-playwright', rule: 'Selectores exactos.', why: '`/añadir/i` caza «Añadir una unidad», `/quitar/i` caza «Quitar una unidad», `.first()` coge el input oculto de escritorio.', howToApply: 'getByRole con name exacto; el contador del carrito va en aria-label.' },
        { id: 'no-afirmar-sin-lectura', rule: 'Nunca decir «listo/desplegado/conectado» sin una lectura en vivo que lo demuestre.', why: 'Un despliegue fallido deja el contenedor viejo sirviendo.', howToApply: 'Comprobar el bundle publicado, el endpoint y la versión servida tras cada despliegue.' },
      ],
    },
  ],
  checks: [
    { id: 'verificar-cobro-csp', evidenceKind: 'contract', purpose: 'La URL del cobro que compila la web está en connect-src de la CSP de cada tienda.', command: 'node scripts/verificar-cobro-csp.mjs', failsWhen: 'Un origen del cobro no aparece en la CSP de hosting.' },
    { id: 'verificar-despliegue-secretos', evidenceKind: 'security-secrets', purpose: 'Ningún fichero sensible sobrevive al filtro de cada contexto de `railway up`.', command: 'node scripts/verificar-despliegue-secretos.mjs', failsWhen: 'Un .env, clave, hoja de cálculo o volcado viajaría al build.' },
    { id: 'verificar-catalogo', evidenceKind: 'contract', purpose: 'Catálogo coherente: SKU únicos ≤40, packs válidos, tachado > precio, disponibilidad solo con stock, titular ↔ catálogo.', command: 'node scripts/verificar-catalogo.mjs', failsWhen: 'Colisiones de SKU/id, packs imposibles, algo disponible sin stock.' },
    { id: 'verificar-contraste', evidenceKind: 'accessibility', purpose: 'Texto de los temas activos a 4,5:1 (WCAG 2.2 AA).', command: 'node scripts/verificar-contraste.mjs', failsWhen: 'Cualquier par texto/fondo por debajo de AA.' },
    { id: 'verificar-precios', evidenceKind: 'unit', purpose: 'Ninguna cuenta publicada («33 batidos a 0,75 €») está mal.', command: 'node scripts/verificar-precios.mjs', failsWhen: 'Una cifra por toma/día no cuadra con precio y formato.' },
    { id: 'verificar-legal', evidenceKind: 'manual-review', purpose: 'Datos LSSI completos en el contenido de Medusa.', command: 'PUBLICO=1 node scripts/verificar-legal.mjs', failsWhen: 'Falta domicilio, teléfono o correo publicados.' },
    { id: 'verificar-medusa', evidenceKind: 'typecheck', purpose: 'services/medusa compila aunque esté fuera del workspace.', command: 'node scripts/verificar-medusa.mjs', failsWhen: 'Tipos del panel/importador no cuadran con Medusa v2.' },
    { id: 'verificar-seo', evidenceKind: 'e2e', purpose: 'HTML construido: títulos únicos, descripción ≤160, canónica, sin señales contradictorias.', command: 'PUBLICO=1 node scripts/verificar-seo.mjs', failsWhen: 'Títulos duplicados, canónica mal, noindex accidental.' },
    { id: 'verificar-cookies', evidenceKind: 'security-sast', purpose: 'Cero cookies y cero terceros en el HTML construido.', command: 'PUBLICO=1 node scripts/verificar-cookies.mjs', failsWhen: 'Aparece un rastreador o dominio externo.' },
    { id: 'verificar-imagenes-responsive', evidenceKind: 'e2e', purpose: 'Imágenes contenidas, sin controles tapándolas, sin rotas, sin scroll horizontal, en Chromium y WebKit a 6 anchos.', command: 'node scripts/verificar-imagenes-responsive.mjs', failsWhen: 'Una imagen desborda, se tapa o se rompe.' },
    { id: 'verificar-encuadres-productos', evidenceKind: 'e2e', purpose: 'Escala visual y píxeles originales de las fotos protegidos.', command: 'node scripts/verificar-encuadres-productos.mjs', failsWhen: 'Un encuadre cambia de escala o una foto pierde sus píxeles originales.' },
    { id: 'suite-cobro', evidenceKind: 'integration', purpose: 'Camino del dinero: valoración, cupones, webhook, espejo Medusa, facturas, sala de espera.', command: 'pnpm --filter @tienda/checkout test', failsWhen: 'Cualquier prueba del cobro falla.' },
    { id: 'suite-ui', evidenceKind: 'unit', purpose: 'Kit de interfaz: carrito, pop-ups, packs.', command: 'pnpm --filter @tienda/ui test', failsWhen: 'Cualquier prueba del kit falla.' },
    { id: 'sesion-real', evidenceKind: 'deploy-smoke', purpose: 'Una sesión de pago real desde el dominio publicado con el total, el IVA y la factura esperados, caducada después.', command: 'POST /checkout desde el dominio real → GET /v1/checkout/sessions/{id} → POST …/expire', failsWhen: 'El total de Stripe difiere del carrito o falta la factura/IVA.' },
  ],
  requiredEvidence: ['typecheck', 'unit', 'integration', 'contract', 'e2e', 'accessibility', 'security-secrets', 'deploy-smoke'],
  bootstrap: [
    { order: 1, step: 'Registrar el proyecto en el control plane con la etiqueta `stack:medusa-commerce` y crear la spec 001 del lanzamiento.', doneWhen: 'developer_project_snapshot devuelve el stack y el gate exige sus evidencias.' },
    { order: 2, step: 'Clonar la plantilla (`starter.clone`), no escribir el monorepo: trae el kit de interfaz, el cobro, Medusa con sus módulos, los porteros y un catálogo de demostración.', doneWhen: 'pnpm test y pnpm build pasan en el clon sin tocar nada.' },
    { order: 3, step: 'Rellenar la ficha de marca con datos CONFIRMADOS por el dueño y ejecutar `starter.configure`; lo no confirmado queda como pending(), nunca inventado.', doneWhen: 'nueva-tienda termina sin errores, `pnpm configurar --comprobar` está al día y el checklist del dueño está entregado.' },
    { order: 4, step: 'Desplegar Medusa (v2) en Railway del dueño con Postgres, Redis, volumen de fotos y panel en español; un canal por tienda con el nombre de `canalMedusa`; store renombrada.', doneWhen: 'El panel abre en español y hay un canal por tienda.' },
    { order: 5, step: 'Importar el catálogo real del cliente (su inventario, no suposiciones) con handle con prefijo, perfil de envío, stock y fotos originales; packs como kits de inventario. Borrar el catálogo y los packshots DEMO.', doneWhen: 'verificar-catalogo pasa, el sync genera los JSON y no queda ningún producto de demostración.' },
    { order: 6, step: 'Desplegar el cobro en Railway del dueño con su Stripe; crear el webhook por API en la versión que espera el código y el proveedor de pago propio en Medusa.', doneWhen: 'Un pago de prueba crea el pedido en Medusa con pago capturado, factura con el IVA de la tienda y un reembolso desde el panel aparece en Stripe.' },
    { order: 7, step: 'Ajustar la tienda a la marca sin tocar el kit: textos en site.config.ts, campañas oficiales en data/campanas-marcas.json, encuadres de fotos y código de bienvenida en Medusa.', doneWhen: 'Primera tarjeta ≤ ~360 px del top; capturas en 6 anchos y 2 motores sin desbordes ni errores de consola.' },
    { order: 8, step: 'Publicar con `pnpm publicar`: cobro primero con --ci, web por API de Hosting en el Firebase del dueño, dominios por CNAME, CSP y ALLOWED_ORIGINS del dominio real.', doneWhen: 'Sesión real desde el dominio con total, IVA y factura correctos, caducada después.' },
    { order: 9, step: 'Encender el publicador nocturno (secretos + PUBLICAR_ACTIVO=true) y dejar main empujado; el dueño confirma sus ajustes de Stripe.', doneWhen: 'El nocturno corre con porteros en modo duro y los puntos de `starter.ownerOnly` están cerrados.' },
  ],
};
